import {
  pgTable,
  serial,
  text,
  timestamp,
  boolean,
  integer,
  numeric,
  real,
  varchar,
} from "drizzle-orm/pg-core";

export const logs = pgTable("logs", {
  id: serial("id").primaryKey(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  text: text("text").notNull(),
});

export const leads = pgTable("leads", {
  id: serial("id").primaryKey(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  text: text("text").notNull(),
});

// Column names are lowercase because PostgreSQL folds unquoted identifiers to lowercase.
export const productInsuranceRate = pgTable("productinsurancerate", {
  productInsuranceRateId: integer("productinsurancerateid").primaryKey(),
  icssProductDwellingQuoteRateId: integer("icssproductdwellingquoterateid"),
  ratePlanId: integer("rateplanid"),
  productId: integer("productid"),
  city: varchar("city", { length: 60 }),
  county: varchar("county", { length: 60 }),
  state: varchar("state", { length: 2 }),
  zipcode: varchar("zipcode", { length: 10 }),
  tier: varchar("tier", { length: 10 }),
  deductibleAmount: varchar("deductibleamount", { length: 20 }),
  deductibleNamedStorm: varchar("deductiblenamedstorm", { length: 20 }),
  startDate: timestamp("startdate"),
  endDate: timestamp("enddate"),
  isInstitutional: boolean("isinstitutional").notNull(),
  isIndividual: boolean("isindividual").notNull(),
  rateStatus: varchar("ratestatus", { length: 20 }),
  rateStatusReason: varchar("ratestatusreason", { length: 50 }),
  insuranceCompany: varchar("insurancecompany", { length: 100 }),
  insuranceCompanyNaic: varchar("insurancecompanynaic", { length: 10 }),
  dwellingAmountInTiv: boolean("dwellingamountintiv").notNull(),
  additionalBuildingAmountInTiv: boolean("additionalbuildingamountintiv").notNull(),
  businessPersonalPropertyInTiv: boolean("businesspersonalpropertyintiv").notNull(),
  annualRentInTiv: boolean("annualrentintiv").notNull(),
  pricePerSqftMin: numeric("pricepersqftmin", { precision: 19, scale: 2 }),
  businessPersonalPropertyCoverage: varchar("businesspersonalpropertycoverage", { length: 25 }),
  waterBackupCoverage: varchar("waterbackupcoverage", { length: 25 }),
  windHailCoverage1: varchar("windhailcoverage1", { length: 25 }),
  windHailCoverage2: varchar("windhailcoverage2", { length: 25 }),
  annualRentCoverage: varchar("annualrentcoverage", { length: 25 }),
  floodCoverage: varchar("floodcoverage", { length: 25 }),
  earthquakeCoverage: varchar("earthquakecoverage", { length: 25 }),
  umbrellaCoverage: varchar("umbrellacoverage", { length: 25 }),
  generalLiabilityRate: numeric("generalliabilityrate", { precision: 19, scale: 2 }),
  additionalLiabilityRatio: real("additionalliabilityratio"),
  triaRate: real("triarate"),
  taxRate: real("taxrate"),
  companyFee: numeric("companyfee", { precision: 19, scale: 2 }),
  brokerFee: numeric("brokerfee", { precision: 19, scale: 2 }),
  propertyRate1: real("propertyrate1"),
  propertyRate2: real("propertyrate2"),
  createUserId: integer("createuserid"),
  modifyUserId: integer("modifyuserid"),
  createDate: timestamp("createdate").notNull().defaultNow(),
  modifyDate: timestamp("modifydate"),
  active: boolean("active").notNull(),
});
