CREATE TABLE IF NOT EXISTS ProductInsuranceRate (
    ProductInsuranceRateID integer generated always as identity primary key,
    ICSSProductDwellingQuoteRateID integer NULL,
    RatePlanID integer NULL,
    ProductID integer NULL,
    City varchar(60) NULL,
    County varchar(60) NULL,
    State varchar(2) NULL,
    Zipcode varchar(10) NULL,
    Tier varchar(10) NULL,
    DeductibleAmount varchar(20) NULL,
    DeductibleNamedStorm varchar(20) NULL,
    StartDate timestamp NULL,
    EndDate timestamp NULL,
    IsInstitutional boolean NOT NULL,
    IsIndividual boolean NOT NULL,
    RateStatus varchar(20) NULL,
    RateStatusReason varchar(50) NULL,
    InsuranceCompany varchar(100) NULL,
    InsuranceCompanyNAIC varchar(10) NULL,
    DwellingAmountInTiv boolean NOT NULL,
    AdditionalBuildingAmountInTiv boolean NOT NULL,
    BusinessPersonalPropertyInTiv boolean NOT NULL,
    AnnualRentInTiv boolean NOT NULL,
    PricePerSqftMin numeric(19,2) NULL,
    BusinessPersonalPropertyCoverage varchar(25) NULL,
    WaterBackupCoverage varchar(25) NULL,
    WindHailCoverage1 varchar(25) NULL,
    WindHailCoverage2 varchar(25) NULL,
    AnnualRentCoverage varchar(25) NULL,
    FloodCoverage varchar(25) NULL,
    EarthquakeCoverage varchar(25) NULL,
    Umbrellacoverage varchar(25) NULL,
    GeneralLiabilityRate numeric(19,2) NULL,
    AdditionalLiabilityRatio real NULL,
    TRIARate real NULL,
    TaxRate real NULL,
    CompanyFee numeric(19,2) NULL,
    BrokerFee numeric(19,2) NULL,
    PropertyRate1 real NULL,
    PropertyRate2 real NULL,
    CreateUserID integer NULL,
    ModifyUserID integer NULL,
    CreateDate timestamp NOT NULL DEFAULT NOW(),
    ModifyDate timestamp NULL,
    Active boolean NOT NULL
);